# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - main

variables:
  terraformVersion: 0.14.4
  timeoutInMinutes: 60
  agentPool: 'ubuntu-18.04'
  build: $(Build.BuildNumber)
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  connectedServiceName: DCD-CFT-Sandbox
  keyVaultName: infra-vault-sandbox
  secretsFilter: 'azure-devops-token'
      

stages:
  - stage: Precheck
    jobs:
      - template: pipeline/templates/precheck/precheck.yaml
        parameters: 
          timeoutInMinutes: ${{ variables.timeoutInMinutes}}
          terraformVersion: ${{ parameters.terraformVersion}}
          connectedServiceName: ${{ variables.connectedServiceName }}
