# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

pool:
  vmImage: "ubuntu-latest"

variables:
  terraformVersion: 0.14.5
  timeoutInMinutes: 60
  agentPool: 'ubuntu-latest'
  build: $(Build.BuildNumber)
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  connectedServiceName: DCD-CFT-Sandbox
  keyVaultName: infra-vault-sandbox
  project: application
  product: neuvector
  terraformInitSubscription: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  template: vars/input-variables.yaml@cnp-azuredevops-libraries

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

  - name: kvConnectedServiceName
    type: string
    default: DCD-CFT-Sandbox
      
  - name: environments
    displayName: Environment to run
    type: object
    default:
      - deployment: 'neuvector'
        environment: 'stg'
        dependsOn: 'Precheck'
        component: sds-neuvector
      - deployment: 'neuvector'
        environment: 'test'
        dependsOn: 'Precheck'
        component: sds-neuvector
      - deployment: 'neuvector'
        environment: 'dev'
        dependsOn: 'Precheck'
        component: sds-neuvector
      - deployment: 'neuvector'
        environment: 'ithc'
        dependsOn: 'Precheck'
        component: sds-neuvector
      - deployment: 'neuvector'
        environment: 'prod'
        dependsOn: 'Precheck'
        component: sds-neuvector

  - name: location
    displayName: Location
    type: string
    default: 'UK South'
    values:
      - 'UK South'
      - 'UK West'

stages:
  - stage: Precheck
    jobs:
      - job:
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: "infra-vault-sandbox"
              keyvaultSecret: "azure-devops-sp-token"
              serviceConnection: "DCD-CFT-Sandbox"
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each parameter in parameters.environments }}:
    - stage: ${{ parameter.environment }}
      displayName: ${{ parameter.environment }}
      dependsOn: ${{ parameter.dependsOn }}
      jobs:
        - job:
          pool:
            vmImage: ${{ variables.agentPool }}
          steps:
            - template: steps/terraform.yaml@cnp-azuredevops-libraries
              parameters:
                environment: ${{ parameter.environment }}
                tfVarsFile: NULL
                kvConnectedServiceName: ${{ parameters.kvConnectedServiceName }}
                overrideAction: ${{ parameters.overrideAction }}
                component: "sds-neuvector"
                serviceConnection: "OPS-APPROVAL-GATE-${{ upper(parameter.environment) }}-ENVS"
                terraformInitSubscription: ${{ variables.terraformInitSubscription }} 
                product: ${{ variables.product }}
                ${{ if eq(parameter.environment, 'stg') }}:
                  initCommandOptions: -backend-config=resource_group_name=azure-control-stg-rg
                  planCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector -backend-config resource_group_name=azure-control-stg-rg
                ${{ if eq(parameter.environment, 'test') }}:
                  initCommandOptions: -backend-config=resource_group_name=azure-control-test-rg
                  planCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector -backend-config resource_group_name=azure-control-test-rg
                ${{ if eq(parameter.environment, 'dev') }}:
                  initCommandOptions: -backend-config=resource_group_name=azure-control-dev-rg
                  planCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector -backend-config resource_group_name=azure-control-dev-rg
                ${{ if eq(parameter.environment, 'ithc') }}:
                  initCommandOptions:
                  planCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector
                ${{ if eq(parameter.environment, 'prod') }}:
                  initCommandOptions:
                  planCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }} -var activity_name=neuvector
