# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  terraformVersion: 0.14.4
  timeoutInMinutes: 60
  agentPool: 'Azure Pipelines'
  build: $(Build.BuildNumber)
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  connectedServiceName: DCD-CFT-Sandbox
  keyVaultName: infra-vault-sandbox
  secretsFilter: 'azure-devops-token'

stages:
  - stage: Precheck
    jobs:
      - template: templates/precheck/precheck.yaml
        parameters: 
          timeoutInMinutes: ${{ variables.timeoutInMinutes}}
          terraformVersion: ${{ variables.terraformVersion}}
          connectedServiceName: ${{ variables.connectedServiceName }}
